version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v4.26.0
    container_name: v2ray
    restart: always
    ports:
      - "${runPort}:${runPort}"
    command: "v2ray -config=http://${api}/api/vmess_server_config/${nodeId}/?token=${token}"

  v2scar:
    container_name: v2scar
    image: ehco1996/v2scar
    restart: always
    depends_on:
      - v2ray
    links:
      - v2ray
    environment:
      V2SCAR_SYNC_TIME: 60
      V2SCAR_API_ENDPOINT: "http://${api}/api/user_vmess_config/${nodeId}/?token=${token}"
      V2SCAR_GRPC_ENDPOINT: "v2ray:8079"
